### ISSUE TITLE
Typo on planets page. TOI-402.02 listed two times

### ISSUE THREAD

**Issue by Nicholaswogan** [compass-jwst/compass-jwst.github.io#1]
https://compass-jwst.github.io/planets.html

**Comment by jkteske** [comment]
Thanks for catching this, Nick! I also need to update the timelines on this page, so it was an extra helpful ping. :)

**Comment by jkteske** [comment]
Changed "TOI-402.02 (HD 15337 b)" to "TOI-402.01 (HD 15337 b)"
